# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-08 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visit', models.DateTimeField()),
                ('star_hour', models.DateTimeField()),
                ('finish_visit', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='type_visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_visit', models.FloatField()),
                ('creation_visit', models.DateTimeField(default=django.utils.timezone.now)),
                ('type_visit', models.CharField(max_length=200)),
                ('description_visit', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='order_visit',
            name='Orders_visit',
            field=models.ManyToManyField(to='visits.type_visit'),
        ),
    ]
