# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-13 08:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='administrators')),
                ('phone_num', models.CharField(max_length=30)),
                ('administrator_root', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False)),
                ('user_administrator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Administrators',
                'verbose_name': 'Administrator',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('birth_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('age', models.IntegerField()),
                ('start_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('phone_num', models.CharField(max_length=30)),
                ('blood_type', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('observations', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clients')),
                ('status', models.CharField(blank=True, choices=[('PA', 'Pagado'), ('PE', 'Pendiente'), ('AT', 'Atrasado')], default='PA', max_length=2, null=True)),
                ('user_client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_clien', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clients',
                'verbose_name': 'Client',
            },
        ),
    ]
