# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-13 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, choices=[('PA', 'Pagado'), ('PE', 'Pendiente'), ('AT', 'Atrasado')], default='PE', max_length=2, null=True),
        ),
    ]
