# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-07 04:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170606_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='user_administrator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
