# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-13 08:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('picture', models.ImageField(blank=True, upload_to='media/courses/pictures')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
